### ISSUE TITLE
No SVs in the lower half of the plot.

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/Schematize#1]
Taking a look at 
![picturemessage_qibjdowk l35](https://user-images.githubusercontent.com/10184961/69633321-49cfba80-1050-11ea-857e-5bb2a27772ba.png) and browsing together with @josiahseaman through yeast data, I realized, that there are no arrivals or departures below the lower half of the visualization.
Possible reasons:

1. The data really is like this, but this is very very unlikely to impossible.
2. During the component segmentation, something goes wrong.
3. The components are drawn 2x the height they actually should be drawn.

@superjox
What do you think?

**Comment by josiahseaman** [comment]
Turns out the height was being multiplied by 2.
