### ISSUE TITLE
Programmatically switch JSON file being read

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/Schematize#13]
Add config.json to specify the full path to the JSON to be rendered
@6br anything to add?

**Comment by subwaystation** [comment]
Something like https://github.com/vgteam/sequenceTubeMap/blob/master/src/config.json

**Comment by subwaystation** [comment]
Using e.g. fetch function to get the file. Or require from node. Not sure, what is the best way here.

**Comment by subwaystation** [comment]
To clarify @josiahseaman Toshiyuki @6br and I were discussing about how people can easily plug in there file for visualization. This will become important when Hiroyuki and Ben will make use of the odgi -> component_segmentation -> schematize pipeline.

**Comment by josiahseaman** [comment]
STM actually calls out to vg chunk to read in a portion of the file: https://github.com/vgteam/sequenceTubeMap/blob/89047773ad16537c917f723c5e80eaee08081d5d/src/server.js#L193L222

**Comment by josiahseaman** [comment]
I got a really bizarre response when reading a file:
```
fetch('data/run1.B1phi1.i1.seqwish.w100.schematic.json')
			.then(response => response.text())
			.then(jsonResponse => console.log(jsonResponse))

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta
      name="description"
      content="Web site created using create-react-app"
    />
    <link rel="apple-touch-icon" href="logo192.png" />
    <!--
      manifest.json provides metadata used when your web app is installed on a
      user's mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
    -->
    <link rel="manifest" href="/manifest.json" />
    <!--
      Notice the use of  in the tags above.
      It will be replaced with the URL of the `public` folder during the build.
      Only files inside the `public` folder can be referenced from the HTML.

      Unlike "/favicon.ico" or "favicon.ico", "/favicon.ico" will
      work correctly both with client-side routing and a non-root public URL.
      Learn how to configure a non-root public URL by running `npm run build`.
    -->
    <title>Schematize</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    <!--
      This HTML file is a template.
      If you open it directly in the browser, you will see an empty page.

      You can add webfonts, meta tags, or analytics to this file.
      The build step will place the bundled scripts into the <body> tag.

      To begin the development, run `npm start` or `yarn start`.
      To create a production bundle, use `npm run build` or `yarn build`.
    -->

  <script src="/static/js/bundle.js"></script><script src="/static/js/0.chunk.js"></script><script src="/static/js/main.chunk.js"></script><script src="/main.4027b171092b8219eee9.hot-update.js"></script></body>
  <script>
      var button = document.getElementById('btn-download');
      button.addEventListener('click', function (e) {
          var cnvs = document.getElementById('cnvs');
          var dataURL = cnvs.toDataURL('image/png');
          // button.href = dataURL;
          var link = document.createElement('a');
          link.download = "output.png";
          link.href = dataURL;
          document.body.appendChild(link);
          link.click();
          document.body.removeChild(link);
          delete link;
      });
  </script>
</html>
```
I think this might be some kind of default response for a 404?  Maybe.

**Comment by subwaystation** [comment]
So we will have two services:
`odgi` will deliver us the bin id of the entered `path:position`.
This we can then take to `component_segmentation` which will deliver us the appropriate JSON directly ready for visualization.

**Comment by josiahseaman** [comment]
So that will bypass the need to scan through files for the right bin_id, but it doesn't remove the requirement that I need to take a variable name of a filepath and read that specific json file.  I'm going to try this:
```
var fs = require('fs');
 var contents = fs.readFileSync('DATA', 'utf8');
console.log(contents);
```

**Comment by subwaystation** [comment]
At least in theory. But running commands from withing a React App might not be possible?
https://stackoverflow.com/questions/55651665/running-shell-command-through-reactjs-code

**Comment by subwaystation** [comment]
So if we can not start any service within React, this is going to be nasty.

**Comment by subwaystation** [comment]
The only solution I see is to have a Node backend. Which I really don't want to have. It would also break compatibility with JBrowse2.

**Comment by josiahseaman** [comment]
Oh you're right....
JBrowse2 runs entirely off of javascript parsable static files - Using odgi or vg breaks that model completely.  You could write a javascript binary parser for your packed files, but that sounds nasty.   you could have an URL rest API you hit, but that would require some other service know about the files you're serving.  Which only works if we have a set of canon data or if we have a service you can upload new data to.  Neither were in our plan.

**Comment by subwaystation** [comment]
So Robert suggest to take a look at https://webassembly.org/ for our C++ service. Maybe we will have to have everything in C++. But not sure........

**Comment by josiahseaman** [comment]
The fix for my problem was moving data to /public/ folder.  We'll want to do the same for your packed position files.  We can definitely read the files from javascript.  I like the idea of using webassembly to compile either vg or odgi, whichever is easier.  It'll work even better if there's a small sliver of code we can extract from one of these programs to avoid dependencies.

**Comment by subwaystation** [comment]
Nice solution for this problem @josiahseaman :)

**Comment by josiahseaman** [comment]
Feb 24: Schematize still needs more work on file switching, but the foundations have been laid.  Next, we can iterate through the chunk_index to find the correct filename based on store.beginBin.  Then #5 would help in testing switching files and eventually straddling two files.  Though I think we can afford to skip straddling feature development for now.

**Comment by josiahseaman** [comment]
I'm going to perform one more scalability test with a 3GB cancer dataset and then close this issue.

**Comment by josiahseaman** [comment]
I'm going to perform one more scalability test with a 3GB cancer dataset and then close this issue.

**Comment by josiahseaman** [comment]
@tpook92 Path_names should maybe be moved to the bin2file.json since they take up a lot of duplicated space in small chunk files.  This seems a natural place to list haplotype breakpoints, so perhaps we have an associated region file?
