### ISSUE TITLE
[PAP] Show nucleotide positions for every path

### ISSUE THREAD

**Issue by josiahseaman** [graph-genome/Schematize#14]
This is the visualization half of https://github.com/vgteam/odgi/issues/78

**Comment by subwaystation** [comment]
Although we have a median nucleotide position for every path, I think we are not accurate enough. At least I am not perfectly happy with it. As the coverage between bins varies, we could end up with a median position of 345 and a median position of 367, although the bin size was 100bp. That is not intuitive and might confuse newcomers.

What I would like to propose via mouse over for each cell in a bin:

- pathname
- nucleotide start position
- the length of a path in nucleotides; `-path_length` could indicate that the path is reverse

We already have a pathname. And we could change from median to start position relatively easily in `odgi`. Taking the current bin size, the coverage and orientation of a path for that specific bin, we should be able to calculate the actual length of a path.

What do you think? @josiahseaman  @superjox @ekg @6br?

**Comment by 6br** [comment]
For biological application, the actual position is always important. Especially in gene region, the one-bp-scale information sometimes relates to frameshift or exon skipping.
