### ISSUE TITLE
Render nucleotides on the nearest zoom level.

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/Schematize#17]
Current procedure:
* Run odgi with --bin_width=1
* Rest of pipeline: segmentation produces folder with sequence stripped out
* Enter directory name for bin=1 files

What needs changed:
- [ ] ODGI needs to output a FASTA file instead of bin sequence (https://github.com/vgteam/odgi/issues/88)
- [ ] component_segmentation chunks up FASTA in parallel with component dividers
- [ ] Schematize detects small zoom level and... 
    - [ ] Read corresponding FASTA
    - [ ] renders sequence in correct position

![Simplified Design](https://user-images.githubusercontent.com/2256148/78503167-36c9a700-7722-11ea-975a-d6fb88da5172.PNG)

**Comment by CrookedY** [comment]
I am working on this I just forgot to write earlier!

**Comment by josiahseaman** [comment]
Real Actual Data available at https://github.com/graph-genome/component_segmentation/tree/master/data/run1.B1phi1.i1.seqwish.w100

**Comment by josiahseaman** [comment]
I've asked Njagi to collaborate with Hannah on this issue.  Njagi is in EAT timezone, and is available in the mornings.  Hannah is only working after 5pm on work days.
