### ISSUE TITLE
Some links at the top of the view are cut off

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/Schematize#26]
When browsing through the current _arabidopsis thaliana_ data the height of the view does not fit to what is presented in the view. Some links are not rendered properly.
![Screenshot from 2020-03-11 16-26-12](https://user-images.githubusercontent.com/10184961/76507479-2d179100-644d-11ea-9910-e7b0f32069cc.png)

**Comment by josiahseaman** [comment]
I'm pretty sure I caused this when I was getting link navigation to work smoothly.  topOffset is no longer being updated because it updated simultaneous with beginEndBin and was causing stuttering render.

**Comment by josiahseaman** [comment]
Hannah Sewell is going to start on this.
