### ISSUE TITLE
Jump to pangenome position.

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/Schematize#29]
The user enters a pangenome position (is it valid?!) and we render that position and ~200 surrounding bins. We have to mark the position we jumped to in e.g. red and centralize it on the screen #6.

This will be a prerequisite for implementing the connection to the `odgi server`.
@6br @josiahseaman

**Comment by subwaystation** [comment]
I tried for hours and today but I ran into a CORS issue. See https://github.com/yhirose/cpp-httplib/issues/390. It seems that the library I use does not set the response header correctly, although I tried that in the C++ code. Worst case I have to switch the server C++ library. Tons of work, then.

**Comment by josiahseaman** [comment]
I noticed the cpp-httplib issue is closed.  Does that mean you got it to work?  You might find it helpful to start from scratch with tutorial code pasted in. I suspect you can then insert the number you want into the contents at the end.

**Comment by subwaystation** [comment]
Yeah, I actually got it to work. Thanks for the feedback.

**Comment by josiahseaman** [comment]
Needs testing, then we can close this.

**Comment by josiahseaman** [comment]
@jacobwindsor is working on this issue.  CORS headers are still not correct for a new user without odgi setup.  odgi service should be optional.

**Comment by jacobwindsor** [comment]
CORS issue still present (latest Chrome)
![image](https://user-images.githubusercontent.com/5579270/77772930-2b52ed80-7049-11ea-93e1-c76f29952ea9.png)

**Comment by subwaystation** [comment]
The CORS headers can only be set by the server. Without a running `odgi server` it won't work and of course the frontend will complain about the headers.
We can not make the `odgi` part optional. Else we won't be able to jump to a pangenome position.
We can only check if a server instance is running and if not, disable the JUMP button.

**Comment by subwaystation** [comment]
If the problem persists, I think it is besser to talk about this via chat or call.

**Comment by josiahseaman** [comment]
Sounds like we need to chat about a way to switch headers and make odgi optional.  I'm available to talk right now.  Jacob would you also join? https://zoom.us/j/9703818860

**Comment by jacobwindsor** [comment]
I'm not sure it's actually to do with the server. Seems like it might be to do with accessing JSON files from public. See blockingJsonFetch in PangenomeSchematic.js.

On that note, why is there a render blocking xhr request?

**Comment by jacobwindsor** [comment]
Got it, requesting a file that's not there. http://localhost:3000/test_data/run1.B1phi1.i1.seqwish.w100/chunk0_bin100.schematic.json should be http://localhost:3000/test_data/run1.B1phi1.i1.seqwish.w100/chunk00_bin100.schematic.json

**Comment by subwaystation** [comment]
@jacobwindsor you are right, it has nothing to do with the server.
And you are ahead of us. @josiahseaman and I are currently working on a fix. Will get pushed soon.
