### ISSUE TITLE
TypeError: Cannot read property 'files' of undefined

### ISSUE THREAD

**Issue by joehagmann** [graph-genome/Schematize#31]
I get a "meaningful" error message when starting the server:
![image](https://user-images.githubusercontent.com/28984545/77092378-0ee00100-6a0a-11ea-9681-39ce781cc550.png)

then something loads, and when changing the coordinates, I get:
![image](https://user-images.githubusercontent.com/28984545/77092490-27501b80-6a0a-11ea-8b38-31c27bfd1f09.png)

head of bin2file.json:
`{
    "bin_width": 10,
    "json_version": 10,
    "last_bin": 15932,
    "pangenome_length": 159318,
    "files": [
        {
            "file": "chunk000_bin10.schematic.json",
            "first_bin": 0,
            "last_bin": 2
        },
        {
            "file": "chunk001_bin10.schematic.json",
            "first_bin": 3,
            "last_bin": 102
        },
        {
            "file": "chunk002_bin10.schematic.json",
            "first_bin": 103,
            "last_bin": 202
        },
        {
            "file": "chunk003_bin10.schematic.json",
            "first_bin": 203,
            "last_bin": 302
        },
        {
            "file": "chunk004_bin10.schematic.json",
            "first_bin": 303,
            "last_bin": 402
        },
        {
            "file": "chunk005_bin10.schematic.json",
            "first_bin": 403,
            "last_bin": 502
        },
        {
            "file": "chunk007_bin10.schematic.json",
            "first_bin": 503,
            "last_bin": 602
        },`

I changed the `startChunkURL` and `endChunkURL` in ViewportInputsStore.js to this dataset. Do I have to adjust `BeginEndBin` accordingly?

**Comment by josiahseaman** [comment]
This seems like a bad startup.  I would start by reverting the chances to ViewInputStore.js.  Instead, paste the directory name into the user input in the browser.  That's the actual intended path.  If the directory you pasted exists, then it will load in the new data including the first two chunks.
