### ISSUE TITLE
Zooming: Switching between different bin widths

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/Schematize#33]
This is an essential feature to be able to navigate large genomes effectively.  We need to be able to smoothly switch between zoom stacks of JSON files.  That means we have 2 coordinates for calculating filenames: Start_bin, and bin_width.  

**Details:**
- [ ] odgi accepts a list of bin size so it doesn't reload the graph to memory each time. (This may already be true, look at pipeline repository for examples)
- [ ] odgi outputs 1 JSON file for each bin_width level
- [ ] component_segmentation takes in a list of files at different bin_width.  All the same prefix name. (Some thought needs to be added here. Currently bin_width is a command line argument, could be a list)
- [ ] Output: Top level directory-> Bin Width -> chunks at bin width
- [ ] bin2file.json should have a list of chunks at each bin_width.  Currently, there's only one.
- [ ] Schematize: add (+) and (-) zoom buttons and zoom level.  Also depends #22
- [ ] Fetched chunk filenames calculated by: Start_bin, and bin_width.

**Comment by josiahseaman** [comment]
@AndreaGuarracino is working on this from the i22_chunk_url_array branch.
