### ISSUE TITLE
Color cells by copy number and inversion

### ISSUE THREAD

**Issue by josiahseaman** [graph-genome/Schematize#37]
The user should see a visual indication of which rows are inverted.  
![Nested Inversions](https://user-images.githubusercontent.com/2256148/77478519-baf76280-6de3-11ea-9faf-f7158e05cebe.PNG)

Cells with increased copy number should be extra dark (notice GGTT cells with extra traversals).  "Empty" cells currently have some coverage threshold, but this could also be a grayscale color instead.
![Complex Example](https://user-images.githubusercontent.com/2256148/77478544-c5196100-6de3-11ea-809b-814258d45ab3.png)

Coverage and inversion rate are listed for every cell in the Matrix available in this.props.item in MatrixCell and also in the JSON[0:1] entries of each bin cell.
```javascript
export class MatrixCell extends React.Component {
    color(){
        this.props.item[0] // coverage or copy number
        this.props.item[1] // inversion rate, color red if >0.5
```

**Comment by josiahseaman** [comment]
@Jacob Windsor Thanks for joining us.  I think a simple Javascript issue to get started on is https://github.com/graph-genome/Schematize/issues/37  npm install, npm start should get you started with a test dataset.

**Comment by josiahseaman** [comment]
![image](https://user-images.githubusercontent.com/2256148/81226118-90362780-8fa7-11ea-97c4-6c5c39ef3e23.png)

I have some questions about this output.  First, if the majority of individuals are inverted, then maybe the component is backwards?  That might not be an issue with the visualization so much as the data and segmentation.

Second, why am I seeing < where it's not red?  From the cod it looks like these are the same trigger:
https://github.com/graph-genome/Schematize/pull/84/files
Unless the color is being overriden by copy number.  I think this needs to be revisited: https://github.com/graph-genome/Schematize/pull/84/files#r421080071

**Comment by josiahseaman** [comment]
@urbanslug would you please address the issue by making the red darker when we have a change in copy number?

**Comment by urbanslug** [comment]
Is the red not dark enough or would you prefer a specific shade of red?

**Comment by josiahseaman** [comment]
No, the issue is here
https://github.com/graph-genome/Schematize/pull/84/files#r421080071 Copy number coloring overrides inversion coloring (see image).

**Comment by josiahseaman** [comment]
This feature was resolved in the Color Legend issue https://github.com/graph-genome/Schematize/pull/90 and this was never closed by mistake.
