### ISSUE TITLE
Pathname List

### ISSUE THREAD

**Issue by 6br** [graph-genome/Schematize#41]
<img width="1078" alt="2020-03-31_10_04_06" src="https://user-images.githubusercontent.com/12047794/77976313-9a755e00-7337-11ea-9003-f6319b5758e8.png">

I need to have a path list to jump to path at nucleotide position.

**Comment by josiahseaman** [comment]
I agree!  We can pull this out of the bin2file.json which should have a path_name list added from HaploBlocker soon.  Currently the list is inside each chunk.json as "path_names".  A similar issue will be added for a dropdown for data sources.

**Comment by 6br** [comment]
Is there anyone who is working on this issue? otherwise I will solve this.
