### ISSUE TITLE
Link click does not respond

### ISSUE THREAD

**Issue by Mark-Seaman** [graph-genome/Schematize#45]
After merging https://github.com/graph-genome/Schematize/pull/42 the click events do not trigger navigation.

Our test script doc is at https://graph-genome.github.io/testing.html  (see step 11).

The commit b68726b419a3c29d57081c3200ea6642eb326baf has the issue.
Feature works in  82d8fe366009d1e2bf51de6c6aa0b1de5fc16dba 

Owner: @CrookedY

Sorry for merging this without adequate testing.

**Comment by CrookedY** [comment]
I can't assign myself but I'll work on fixing this
