### ISSUE TITLE
TypeError: can't access property "map"

### ISSUE THREAD

**Issue by 6br** [graph-genome/Schematize#47]
When I run Schematize with non-consecutive data, I faced this error.

<img width="1032" alt="2020-04-01 14 35 09" src="https://user-images.githubusercontent.com/12047794/78109388-0937e180-7434-11ea-93a2-25e639e7c135.png">

I suspect this behavior is related to https://github.com/graph-genome/component_segmentation/issues/15.

**Comment by 6br** [comment]
[nonconsecutive_chunks.zip](https://github.com/graph-genome/Schematize/files/4413406/nonconsecutive_chunks.zip)
Data here.
```bash
$ ls nonconsecutive_chunks/
bin2file.json                   chunk0_bin1000.schematic.json   chunk28_bin1000.schematic.json  chunk39_bin1000.schematic.json  chunk56_bin1000.schematic.json
chunk00_bin1000.schematic.json  chunk12_bin1000.schematic.json  chunk30_bin1000.schematic.json  chunk42_bin1000.schematic.json
chunk02_bin1000.schematic.json  chunk17_bin1000.schematic.json  chunk33_bin1000.schematic.json  chunk45_bin1000.schematic.json
chunk04_bin1000.schematic.json  chunk22_bin1000.schematic.json  chunk36_bin1000.schematic.json  chunk50_bin1000.schematic.json
```

**Comment by josiahseaman** [comment]
Let's make sure to always include the SHA, so we're talking about the same thing.  I am using 1a4c157a1e862d3b64ca7408bb764adb19c5489c and I was not able to reproduce your error.

My first recommendation is to make the files bigger by turning up your --cells_per_file in component_segmentation.  The bin2file.json says there's only 32 bins, which don't need to be split over ~10 files.  If you use this bin2file.json instead:
```json
{
    "bin_width": 1000,
    "json_version": 10,
    "last_bin": 32,
    "pangenome_length": 31120,
    "files": [
        {
            "file": "chunk0_bin1000.schematic.json",
            "first_bin": 0,
            "last_bin": 32
        }
    ]
}
```
It will load chunk0_bin1000.json just fine, which contains the whole pangenome.  

![image](https://user-images.githubusercontent.com/2256148/78179023-c834d280-741d-11ea-8368-bb0bfdb1aa1e.png)

**Comment by 6br** [comment]
Thanks, I also solved this issue by changing `--cells_per_file` though we need to find the way to adjust the better parameter.
