### ISSUE TITLE
Schematize has troubles dealing with one file based visualizations

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/Schematize#78]
I tried to use Schematize with a very small graph. `odgi viz` gives me
![svg1 gfa og](https://user-images.githubusercontent.com/10184961/80494678-3a3e0000-8967-11ea-8496-36349fbf0ac6.png)
But Schematize gives me 
![Screenshot from 2020-04-28 15-42-27](https://user-images.githubusercontent.com/10184961/80494736-4cb83980-8967-11ea-9ace-78d8229414f6.png)
I assume because I only have one chunk file. Any ideas on how to quickly fix this?
Here are the files:
[SVG.zip](https://github.com/graph-genome/Schematize/files/4546101/SVG.zip)

**Comment by josiahseaman** [comment]
That is very old code.  Try testing it on the latest master version.

**Comment by subwaystation** [comment]
I did, but ran into 
![image](https://user-images.githubusercontent.com/10184961/80574410-1085e700-8a02-11ea-875e-81457dc05ace.png)

So my JSON version does not match. I tried to trick Schematize by entering `14` manually, but then other errors occurred.

I generated my Schematize input with the latest master of CS https://github.com/graph-genome/component_segmentation/commit/a20d1357dd471cf63e8628cc243a2e3a1f76a8ad which only outputs JSONs of version `13`. Any help appreciated.

**Comment by 6br** [comment]
This is offtopic but `throw MediaError` is not good because `MediaError` is undefined through entire codes.

**Comment by 6br** [comment]
This is also offtopic but I saw this error message when I ran the latest Schematize.
<img width="1189" alt=" 2020-04-29 18 34 25" src="https://user-images.githubusercontent.com/12047794/80584657-f8878500-8a4c-11ea-896c-c2337eebc3df.png">

**Comment by josiahseaman** [comment]
Oh, I'm sorry CS output v13.  I may not have merged CS into master yet.  The data files for v14 can be found here: https://drive.google.com/drive/folders/1S4ooVv4pJLfKAlRe5JqDV4DuTkWBXAZk?usp=sharing

**Comment by josiahseaman** [comment]
v14 was generated from this i43_prerender branch and I've now created a PR.  https://github.com/graph-genome/component_segmentation/pull/45

**Comment by subwaystation** [comment]
Thanks for the data files link! It works as expected. Awesome job.

**Comment by subwaystation** [comment]
> v14 was generated from this i43_prerender branch and I've now created a PR. [graph-genome/component_segmentation#45](https://github.com/graph-genome/component_segmentation/pull/45)

Solved my issue. Thanks @josiahseaman .
