### ISSUE TITLE
Small viz issues with test data

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/Schematize#80]
I visualized [cs_svg1_i43.zip](https://github.com/graph-genome/Schematize/files/4553711/cs_svg1_i43.zip) and got the following:

![Screenshot from 2020-04-29 20-08-06](https://user-images.githubusercontent.com/10184961/80633582-499d7600-8a59-11ea-93a5-bf7bf132c848.png)
I think the viz has the following Issues:

- [x] The yellow link goes from Bin4 to Bin5. But we only see it entering in Bin5.
- [x] Not all nucleotides are rendered, although they are in the FASTA chunk.
- [x] The component connectors are not on the same height as the cells.
- [x] The chunk.JSON also says there is a link from Bin5 to Bin17. Not visible in the viz.

Maybe I missed something, but these are the things I noted.

**Comment by josiahseaman** [comment]
@AndreaGuarracino and I identified what was causing the missing Departure Column at the end of schematic.  Every component should have an extra departure column that is the list of "Adjacent Connectors" going to the next component in the layout.  The next component does not have a matching "Arrivals" column for these adjacent connectors.  Schematize `.slice(0,-1)` slices off the last of every departure correctly.  However, component_segmentation wasn't doing this to the very last component in the file.  [I've now got a commit to fix that](https://github.com/graph-genome/component_segmentation/commit/4cd659e5de08f643daaaccbe419921cbe3ee3517).  Documentation also should be updated for this odd convention.  

In v15 JSON we plan to remove this odd convention with a new field for every component that is "connectors" with a sparse list of indices for individuals (rows).

![image](https://user-images.githubusercontent.com/2256148/81856837-95065880-951e-11ea-98ce-ea986680b497.png)

**Comment by josiahseaman** [comment]
![image](https://user-images.githubusercontent.com/2256148/81873173-672e0d80-9538-11ea-9b35-951bfe14e90d.png)

**Comment by subwaystation** [comment]
Cool, looks much better now!

**Comment by AndreaGuarracino** [comment]
And here the missing nucleotides, including the first one that was always hidden before:

![image](https://user-images.githubusercontent.com/62253982/81907749-8b392f80-95c8-11ea-8247-aaaa54808c11.png)

I will improve the implementation, but it works now.

**Comment by subwaystation** [comment]
Amazing!
Thanks for solving this @AndreaGuarracino + @josiahseaman !
