### ISSUE TITLE
Ready for Figure generation

### ISSUE THREAD

**Issue by josiahseaman** [graph-genome/Schematize#9]
Even more immediate than JBrowse issues 2-8 is the need to get Figures for our paper.  Since the browser context won't be in the paper, we need to focus on just the rendering window.  We can manually input things like start and stop #4 by editing the code.

- [x] Adjacent connectors drawn (this will show whether the path is present)
- [x] Vertical Compression: Never show rows that are not present in the current view window
- [x] Vertical Compression: Stack all the participants to the top of each component to show the proportion that participates in a Link (on by default)

**Comment by subwaystation** [comment]
@josiahseaman Could you please explain the first point? I understand it as a duplicate of #2?
Thanks!

**Comment by subwaystation** [comment]
Ah it just came to my mind, what you meant with adjacent connectors.
So we will need the connectors and still an indication, where the paths starts, right?
Because the connectors only follow a path, but don't indicate the starting or ending bin of a path.

**Comment by josiahseaman** [comment]
100% height of a component = 100% of the individuals which participate in the component.  That way LinkColumn height to be proportional.  eg. 20% or 5% of population has this SV.

**Comment by subwaystation** [comment]
I think we also need:
100% height of a component = 100% of paths in the whole pangenome?
So people can have an idea of the SV regarding all paths crossing the component and all paths in the pangenome.

**Comment by josiahseaman** [comment]
Adjacent connections will show that a path is present in the component, even when it doesn't have any SVs.  Without vertical compression, that does give you an indication of where a path starts or stops (kinda).  But with vertical compression on (no SV phase) that per-row information is not visible.  We could include a special connector symbol for beginning and end, but I think #2 is a low priority.

**Comment by subwaystation** [comment]
I am seeing really weird stuff happening when visualizing `./data/sebastian.Athaliana.all.50000.w100000.schematic.json` when checking out https://github.com/graph-genome/Schematize/commit/71217e38fb7a0dcbcd9b3f39c37012a38c7c22e4.

![Screenshot from 2020-02-03 13-45-52](https://user-images.githubusercontent.com/10184961/73654472-1a5eaf00-468c-11ea-88f9-12f8cd95bdbc.png)
 There is a rectangle directly under download. A link arrow is drawn, but no link column, etc.
Maybe https://github.com/graph-genome/Schematize/blob/71217e38fb7a0dcbcd9b3f39c37012a38c7c22e4/src/App.js#L65 is a problem?

**Comment by subwaystation** [comment]
When taking a look at `./data/sebastian.Athaliana.all.50000.w100000.schematic.1D.json` I get some weird output, too.

![image](https://user-images.githubusercontent.com/10184961/73655141-9c030c80-468d-11ea-83c8-712114883c69.png)

**Comment by subwaystation** [comment]
Ok, I fixed this via https://github.com/graph-genome/Schematize/commit/d0261fbf3cc94e00d47e2ff0e6874b8e0d914181. I suspect, that we might run into other issues related to `.....departures.length - 1` vs. `departures.length` in our code.

![Screenshot from 2020-02-03 15-23-16](https://user-images.githubusercontent.com/10184961/73661233-0457eb00-469a-11ea-9165-fbfe12c3b54d.png)

Still need to adjust the width of the adjacent connectors.

**Comment by subwaystation** [comment]
@josiahseaman As you can see here, the width of the adjacent connectors is too wide. Removing ` *2` in https://github.com/graph-genome/Schematize/blob/0df3163c76ce7bd612da855cc536313814518124/src/ComponentRect.js#L93 takes care of that.
But then the x-coords of most! components and links does not fit anymore. We need to move a component to the left, if we have drawn any connectors. If not, we should not move them.
See e.g. between the 4th and 5th component in the picture above. The space there is one binsPerPixel smaller compared to when a connector was drawn between two components.

**Comment by josiahseaman** [comment]
Adjacent connectors have been added as the last LinkColumn in `departures`.  That's why I added `departures.length - 1`.  The same could probably be done for arrivals as well.  Since this is to reflect a change in the data, any old data not updated to the current format (generated by component_segmentation after 35807d427a07816e6efdec98bac330701899eaad) will render wrong.  

Adjacent connectors should be our column padding size, not binsPerPixel.  Sorry, I didn't know where that came from.  So that we don't run into this in the future, I think I'll introduce a JSON version number which the program checks and raises an error if the data was produced in a different version than what it's expecting.  That'll keep us from getting our data files crossed.  

@ekg may want to do the same thing if there's any plans to update the ODGI bin output.

**Comment by ekg** [comment]
It's not the case that all bins will be connected to adjacent ones. A graph
can have unaligned components, and these won't link to anything else.

**Comment by josiahseaman** [comment]
That's a very interesting point!  Wouldn't their co-occurrence in a Path cause them to be linked?  If they weren't connected to anything, wouldn't the sort move them to the end or beginning?

**Comment by subwaystation** [comment]
> Adjacent connectors have been added as the last LinkColumn in `departures`. That's why I added `departures.length - 1`. The same could probably be done for arrivals as well. Since this is to reflect a change in the data, any old data not updated to the current format (generated by component_segmentation after 35807d427a07816e6efdec98bac330701899eaad) will render wrong.
> 
> Adjacent connectors should be our column padding size, not binsPerPixel. Sorry, I didn't know where that came from. So that we don't run into this in the future, I think I'll introduce a JSON version number which the program checks and raises an error if the data was produced in a different version than what it's expecting. That'll keep us from getting our data files crossed.
> 
> @ekg may want to do the same thing if there's any plans to update the ODGI bin output.

So I raised a false flag by testing with malformed data....... sorry!

**Comment by josiahseaman** [comment]
Thanks for spotting that.  I'm sorry I didn't communicate the data format change more clearly.  I've learned my Lesson.  I think I'll work on the Histogram feature next, but this would be much more effective with a Toggle Input for the user to turn on and off vertical compression.  @subwaystation would you like to try your hand at getting a toggle connected to `store.useVerticalCompression`?

**Comment by josiahseaman** [comment]
All 3 features that I wanted for this issue are now in master.  Mobx state updates could certainly be cleaner, but it meets our MVP needs.  Matrix will be a separate issue.
