### ISSUE TITLE
Switching the pangenome position does not work correctly

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/Schematize#91]
Switching the pangenome position by clicking on `>` does not work. After the click, the view is moved to the right. Part of the viz is cut on the left side and some white space is added on the right side. But no new data is loaded or visualized.

**Comment by AndreaGuarracino** [comment]
Yes, I think the problem could be related to the EndBin management. I am working on this problem in the issue #86.

**Comment by josiahseaman** [comment]
@AndreaGuarracino does fcb0cc7 or your further work close this issue?  If you write `closes #91` in a commit message, it will automatically close when merged to master.

**Comment by AndreaGuarracino** [comment]
Yes, it should be fixed. I didn't know this automatic behavior, thank you.
