### ISSUE TITLE
Displaying colored gene annotations in the top rows

### ISSUE THREAD

**Issue by josiahseaman** [graph-genome/Schematize#99]
Doing this will allow us to show the genes of SARS-CoV-2 as colored paths in the top rows of the pangenome for public release.  This will be a team effort.

- [x] @AndreaGuarracino have you generated the gene FASTA with the NAME= field that will be more Human readable? 
- [x] All gene path name mentioned in metadata.json.  This can be generated from the genes.fasta headers that @AndreaGuarracino  created in the earlier step to get provenance coloring
- [x] Genes are sorted to the top rows - this may deserve its own issue.
- [x] @mandosoft can concatenate that to our 169 sample dataset and rerun graph creation and place it on Arvados. 
- [x] This may require @subwaystation to update the path position server. I'm not sure how deterministic the sort is?

**Comment by josiahseaman** [comment]
@AndreaGuarracino would you please write out what is required to get "Genes are sorted to the top rows"?  I remember I started with a special rule for the reference genome, name in compressed_row_mapping.

**Comment by josiahseaman** [comment]
I believe this file has the 169 SARS2 samples in it, where the first one is the reference genome.  It has 169 FASTA entries in it and that can't be a coincidence.   https://drive.google.com/file/d/1ssySWswTJzXW_Dg65YmczilqNUQ3Mp9E/view?usp=sharing

**Comment by josiahseaman** [comment]
# Sorting Genes to the Top Rows
* All Genes are listed in the metadata.json here: https://drive.google.com/file/d/1j2OkN4ChhkWRnq_rKPN4eZwwtEPCQ1ej/view?usp=sharing
* metadata.json is read in thanks to @superjox and #67 you can look at the commits in this issue to see the code changed
* In [ComponentRect.js: compress_visible_rows](https://github.com/graph-genome/Schematize/blob/gene_annotations/src/ComponentRect.js#L38) a Set of current occupants is constructed and an order is derived from that.  
* You need to hijack this ordering and create a separate list of "highPriorityRows" which includes anything mentioned in metadata.json.  
* The final rowMapping return will be [...highPriorityRows, ...otherRows]
* You can check for the presence of metaData like [this example](https://github.com/graph-genome/Schematize/blob/gene_annotations/src/ComponentRect.js#L77):
```javascript
let pathName = this.props.pathNames[uncompressed_y];
let metaData = this.props.store.metaData;
      if (metaData.get(pathName) !== undefined) {
      // highPriorityRows
      }
```

**Comment by AndreaGuarracino** [comment]
The path in the metadata are visualized on the top.
![image](https://user-images.githubusercontent.com/62253982/87055155-44506a80-c204-11ea-94bf-b1c8323fb57f.png)

Now the reference should be visualized close to them.

**Comment by AndreaGuarracino** [comment]
SARS-CoV-2 pangenome with 169 individuals + 11 gene annotations

The annotations are on the top, followed by the reference in black:

![image](https://user-images.githubusercontent.com/62253982/87084323-55ae6c80-c22e-11ea-8d97-a6723c396762.png)

**Comment by subwaystation** [comment]
All things are ticked! Thanks @AndreaGuarracino @mandosoft @josiahseaman !
